"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=grain, mlt_service=grain
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_grain(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    noise: float = 40.0,
    contrast: float = 160.0,
    brightness: float = 70.0,
) -> dict:
    """Grain -- Grain over the image."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='grain',
        kdenlive_id='grain',
        params={'noise': noise, 'contrast': contrast, 'brightness': brightness},
    )
