"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=scratchlines, mlt_service=lines
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_scratchlines(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    keyframes: str = "",
) -> dict:
    """Scratch Lines -- Scratch lines over the picture."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='lines',
        kdenlive_id='scratchlines',
        params={},
        keyframes=keyframes,
    )
