"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=dust, mlt_service=dust
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_dust(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    keyframes: str = "",
) -> dict:
    """Dust -- Add dust and specks to the video, as in old movies."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='dust',
        kdenlive_id='dust',
        params={},
        keyframes=keyframes,
    )
