"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=frei0r_scanline0r, mlt_service=frei0r.scanline0r
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_frei0r_scanline0r(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
) -> dict:
    """scanline0r -- Interlaced black lines."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='frei0r.scanline0r',
        kdenlive_id='frei0r_scanline0r',
        params={},
    )
