"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=tcolor, mlt_service=tcolor
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_tcolor(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    keyframes: str = "",
) -> dict:
    """Technicolor -- Oversaturate the color in video, like in old Technicolor movies."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='tcolor',
        kdenlive_id='tcolor',
        params={},
        keyframes=keyframes,
    )
