"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=scratchlines, mlt_service=lines
"""
from __future__ import annotations

import xml.etree.ElementTree as ET

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    _ok,
    _err,
    _require_workspace,
    register_effect_wrapper,
)
from workshop_video_brain.edit_mcp.adapters.kdenlive import patcher
from workshop_video_brain.edit_mcp.adapters.kdenlive.parser import parse_project
from workshop_video_brain.edit_mcp.adapters.kdenlive.serializer import serialize_project
from workshop_video_brain.workspace import create_snapshot


@register_effect_wrapper
def effect_scratchlines(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    keyframes: str = "",
) -> dict:
    """Scratch Lines -- Scratch lines over the picture."""
    try:
        ws_path, _ws = _require_workspace(workspace_path)
        project_path = ws_path / project_file
        if not project_path.exists():
            return _err(f"Project file not found: {project_file}")

        project = parse_project(project_path)

        # Build filter XML
        filt = ET.Element("filter")
        svc = ET.SubElement(filt, "property", {"name": "mlt_service"})
        svc.text = 'lines'
        kid = ET.SubElement(filt, "property", {"name": "kdenlive_id"})
        kid.text = 'scratchlines'

        params: dict[str, object] = {}
        for _mlt_name, _value in params.items():
            if isinstance(_value, bool):
                _str_val = "1" if _value else "0"
            else:
                _str_val = str(_value)
            _prop = ET.SubElement(filt, "property", {"name": _mlt_name})
            _prop.text = _str_val

        if keyframes:
            _kf = ET.SubElement(filt, "property", {"name": "keyframes"})
            _kf.text = keyframes

        xml_string = ET.tostring(filt, encoding="unicode")

        # Determine insertion index (end of stack)
        existing = patcher.list_effects(project, (track, clip))
        insert_index = len(existing)

        create_snapshot(
            ws_path,
            project_path,
            description="before_effect_scratchlines",
        )
        patcher.insert_effect_xml(project, (track, clip), xml_string, insert_index)
        snap = create_snapshot(
            ws_path,
            project_path,
            description="after_effect_scratchlines",
        )
        serialize_project(project, project_path)

        return _ok({
            "effect_index": insert_index,
            "snapshot_id": snap.snapshot_id,
        })
    except (ValueError, FileNotFoundError, IndexError) as exc:
        return _err(str(exc))
