"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=frei0r_aech0r, mlt_service=frei0r.aech0r
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_frei0r_aech0r(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    _0: float = 0.15,
    _1: bool = False,
    _2: bool = False,
    _3: bool = False,
    _4: bool = False,
    keyframes: str = "",
) -> dict:
    """Analog Video Echo -- Create an analog video echo."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='frei0r.aech0r',
        kdenlive_id='frei0r_aech0r',
        params={'0': _0, '1': _1, '2': _2, '3': _3, '4': _4},
        keyframes=keyframes,
    )
