"""GENERATED by effect_wrapper_gen. Do not edit by hand.

Regenerate with:
    uv run workshop-video-brain catalog regenerate-wrappers

Source effect: kdenlive_id=frei0r_letterb0xed, mlt_service=frei0r.letterb0xed
"""
from __future__ import annotations

from workshop_video_brain.edit_mcp.server.tools_helpers import (
    apply_simple_effect,
    register_effect_wrapper,
)


@register_effect_wrapper
def effect_frei0r_letterb0xed(
    workspace_path: str,
    project_file: str,
    track: int,
    clip: int,
    Transparency: bool = False,
    keyframes: str = "",
) -> dict:
    """Letter-boxing -- Adds black borders at the top and bottom for that widescreen cinema look."""
    return apply_simple_effect(
        workspace_path,
        project_file,
        track,
        clip,
        mlt_service='frei0r.letterb0xed',
        kdenlive_id='frei0r_letterb0xed',
        params={'Transparency': Transparency},
        keyframes=keyframes,
    )
